name: Docker image

on:
   workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: repo checkout
      uses: actions/checkout@v2
  
    - name: Build image
      run: docker build . --file Dockerfile --tag my-webpage-github:latest
  
