name: Docker image

on:
   workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: repo checkout
      uses: actions/checkout@v2
      
    - name: login to docker hub  
      env:
         username: ${{secrets.DOCKER_USERNAME}}
         password: ${{secrets.DOCKER_PASSWORD}}
      run: |
         docker login -u $username -p $password 
    - name: build the docker image
      run: |
         docker build . -f Dockerfile -t $username/demo-image-1:latest
    - name: push the docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/demo-image-1:latest
