name: Docker image

on:
   workflow_dispatch:

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
    - name: repo checkout
      uses: actions/checkout@v2
      
    - name: login to docker hub  
      env:
         username: ${{secrets.DOCKERHUB_USERNAME}}
         password: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
         docker login -u $username -p $password 
    - name: build the docker image
      run: |
         ls -la 
         docker build . -f Dockerfile -t dhruvin30/demo-image-test:latest
    - name: push the docker image
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/demo-image-test:latest
